### ISSUE TITLE
Are you going add the new features from the base game?

### ISSUE THREAD

**Issue by Andrew2o0** [FNF-CNE-Devs/CodenameEngine#360] opened 2024-07-29 01:00 UTC
Uh, are you going to add the new content. they have weekend 1 n' stuff. when are you going to add them. it's been 2 months.

**Comment by NexIsDumb** [comment] 2024-07-29 07:21
oh nono im actually working on it in the new update of cne
altho the problem is that i had to pause it to help out other mods i was in plus rn my pc its in a reparing shop lmao
unfortunately besides me none of the other devs was helping me since they were doing other features of the engine
i'll continue it when mods like dustin or hymns dont need my help for a while as soon as my pc is back

**Comment by NexIsDumb** [comment] 2024-08-27 00:51
imma close this, answered question

**Closed by NexIsDumb** 2024-08-27 00:51 UTC
Labels: enhancement
